test coverage

diff --git a/.github/workflows/jacoco.yml b/.github/workflows/jacoco.yml
--- a/.github/workflows/jacoco.yml
+++ b/.github/workflows/jacoco.yml
@@ -1,66 +1,40 @@
-name: build
+name: Java CI with JaCoCo
 
 on:
   push:
-    branches: [ feat/CS-36689-compare-merge-branch ]
-    paths: [ '**.java', '.github/workflows/jacoco.yml', 'pom.xml' ]
-  pull_request:
-    branches: [ feat/CS-36689-compare-merge-branch ]
-  workflow_dispatch:
+    branches:
+      - main
 
 jobs:
-  jacoco-java-maven:
-
+  build-and-test:
     runs-on: ubuntu-latest
-    
+
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v2
 
+      - name: Set up JDK 11
+        uses: actions/setup-java@v2
+        with:
+          java-version: "11"
 
-    - name: Set up JDK 11
-      uses: actions/setup-java@v3
-      with:
-        distribution: 'adopt'
-        java-version: '11'
+      - name: Build with Maven
+        run: mvn clean package
 
-    - name: Build with Maven
-      run: mvn -B package -Pcoverage
+      - name: Run Tests with JaCoCo
+        run: mvn jacoco:prepare-agent test jacoco:report
 
-    - name: Generate JaCoCo badge
-      id: jacoco
-      uses: cicirello/jacoco-badge-generator@v2.9.0
-      with:
-        badges-directory: badges
-        generate-branches-badge: true
-        generate-summary: true
-
-    - name: Log coverage percentages to workflow output
-      run: |
-        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
-        echo "branches = ${{ steps.jacoco.outputs.branches }}"
-
-    - name: Upload JaCoCo coverage report as a workflow artifact
-      uses: actions/upload-artifact@v3
-      with:
-        name: jacoco-report
-        path: target/site/jacoco/
-
-
-    - name: Comment on PR with coverage percentages
-      if: ${{ github.event_name == 'pull_request' }}
-      run: |
-        REPORT=$(<badges/coverage-summary.json)
-        COVERAGE=$(jq -r '.coverage' <<< "$REPORT")%
-        BRANCHES=$(jq -r '.branches' <<< "$REPORT")%
-        NEWLINE=$'\n'
-        BODY="## JaCoCo Test Coverage Summary Statistics${NEWLINE}* __Coverage:__ ${COVERAGE}${NEWLINE}* __Branches:__ ${BRANCHES}"
-        gh pr comment ${{github.event.pull_request.number}} -b "${BODY}"
-      continue-on-error: true
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-    - name: Get the Coverage info
-      run: |
-        echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
-        echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
+      - name: Check Code Coverage
+        run: |
+          total_lines=$(xmllint --xpath 'string(//counter[@type="LINE"]/@covered)' target/site/jacoco/jacoco.xml)
+          total_lines=${total_lines:-0}
+          total_missed=$(xmllint --xpath 'string(//counter[@type="LINE"]/@missed)' target/site/jacoco/jacoco.xml)
+          total_missed=${total_missed:-0}
+          total_percentage=$(awk "BEGIN { pc=100*${total_lines}/(${total_lines}+${total_missed}) } { printf \"%f\", pc }")
+          echo "Total Coverage Percentage: $total_percentage"
+          if (( $(bc <<< "$total_percentage < 80.0") )); then
+            echo "Code Coverage is below 80% - failing the CI build."
+            exit 1
+          else
+            echo "Code Coverage is satisfactory - CI build passed."
+          fi
